# Generated by Django 2.2.2 on 2021-01-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210121_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
