# Generated by Django 2.2.2 on 2021-01-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_school_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='school',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
